---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - htop
    - rsync

- name: install cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - flux
    - iterm2
